# -*- coding: utf-8 -*-
# Deployment settings for HelloCPP.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['D:/tools/Marmalade/6.3/s3e/makefile_builder/mkb.py', 'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/HelloCPP.mkb', '--deploy-only']
mkb = 'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/HelloCPP.mkb'
mkf = ['d:\\tools\\marmalade\\6.3\\modules\\iwgl\\iwgl.mkf', 'd:\\tools\\marmalade\\6.3\\modules\\iwutil\\iwutil.mkf', 'd:\\tools\\marmalade\\6.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'd:\\tools\\marmalade\\6.3\\modules\\third_party\\libpng\\libpng.mkf', 'd:\\tools\\marmalade\\6.3\\modules\\third_party\\zlib\\zlib.mkf', 'd:\\tools\\cocos2dx\\cocos2dx\\proj.marmalade\\cocos2dx.mkf', 'd:\\tools\\cocos2dx\\cocos2dx\\platform\\third_party\\marmalade\\freetype.mkf', 'd:\\tools\\cocos2dx\\cocos2dx\\platform\\third_party\\marmalade\\libtiff.mkf', 'd:\\tools\\cocos2dx\\cocos2dx\\platform\\third_party\\marmalade\\libwebp.mkf', 'd:\\tools\\cocos2dx\\external\\box2d\\proj.marmalade\\box2d.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('d:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/Resources/fonts', 'fonts', 0),
    ('d:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/Resources/ipad', 'ipad', 0),
    ('d:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/Resources/ipadhd', 'ipadhd', 0),
    ('d:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/Resources/iphone', 'iphone', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'HelloCPP'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'HelloCPP'
    long_caption = 'HelloCPP'
    version = [0, 0, 1]
    config = ['d:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/Resources/app.icf']
    data_dir = 'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/Resources'
    iphone_link_lib = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    iphone_link_libdirs = []
    iphone_link_opts = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    win32_ext_dll = []
    android_so = []
    osx_ext_dll = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_gcc_x86/HelloCPP.so',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_gcc_x86/HelloCPP.so',
                 },
         'mips_gcc' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_gcc_mips/HelloCPP.so',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_gcc_mips/HelloCPP.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_gcc_arm/HelloCPP.s3e',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_gcc_arm/HelloCPP.s3e',
                 },
         'mips' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_gcc_mips/HelloCPP.so',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_gcc_mips/HelloCPP.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_gcc_x86_android/HelloCPP.so',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_gcc_x86_android/HelloCPP.so',
                 },
         'arm' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_arm/HelloCPP.s3e',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_arm/HelloCPP.s3e',
                 },
         'x86' : {
                   'debug'   : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Debug_HelloCPP_VC10X_x86/HelloCPP.s86',
                   'release' : r'd:/tools/cocos2dx/samples/Cpp/HelloCpp-Box2D-CollisionTest-2.1.2/proj.marmalade/build_hellocpp_vc10x/Release_HelloCPP_VC10X_x86/HelloCPP.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
